Repository zardoy/minecraft-web-client, pull requests merged in 2025-02, with the labels that each got.

#253 fix: kick screen would allow going back with lockConnect parameter
  src/appParams.ts
  src/downloadAndOpenFile.ts
  src/googledrive.ts
  src/index.ts
  src/loadSave.ts
  src/optionsStorage.ts
  src/react/AddServerOrConnect.tsx
  src/react/AppStatus.tsx
  src/react/PauseScreen.tsx
  src/react/ServersListProvider.tsx
Labels: Review effort [1-5]: 2

#262 feat: reimplement auto version - fix bugs, +config, make faster!!
  patches/minecraft-protocol@1.53.0.patch
  patches/minecraft-protocol@1.54.0.patch
  pnpm-lock.yaml
  scripts/makeOptimizedMcData.mjs
  src/appParams.ts
  src/connect.ts
  src/importsWorkaround.js
  src/index.ts
  src/mineflayer/mc-protocol.ts
  src/mineflayer/minecraft-protocol-extra.ts
  src/optionsGuiScheme.tsx
  src/optionsStorage.ts
  src/shims/minecraftData.ts
  src/shims/patchShims.ts
Labels: Review effort [1-5]: 3

#268 feat: Connections issues icon & reconnect button
  cypress/e2e/index.spec.ts
  cypress/minecraft-server.mjs
  src/globalState.ts
  src/index.ts
  src/mineflayer/mc-protocol.ts
  src/mineflayer/websocket-core.ts
  src/react/AppStatus.tsx
  src/react/AppStatusProvider.tsx
  src/react/IndicatorEffects.css
  src/react/IndicatorEffects.tsx
  src/react/IndicatorEffectsProvider.tsx
  src/react/ServersListProvider.tsx
Labels: Review effort [1-5]: 2

#265 fix: skins of NPCs would not get applied properly
  prismarine-viewer/examples/scenes/main.ts
  prismarine-viewer/viewer/lib/entities.ts
  prismarine-viewer/viewer/lib/entity/EntityMesh.js
  prismarine-viewer/viewer/lib/entity/armorModels.json
  prismarine-viewer/viewer/lib/mesher/models.ts
  prismarine-viewer/viewer/lib/mesher/shared.ts
  prismarine-viewer/viewer/lib/worldrendererThree.ts
  src/entities.ts
Labels: Review effort [1-5]: 3

#274 fix: resource pack armor textures and leather armor color bleed
  renderer/viewer/lib/entities.ts
  renderer/viewer/lib/entity/armorModels.ts
  renderer/viewer/lib/entity/objModels.js
  renderer/viewer/lib/worldrendererCommon.ts
  src/resourcePack.ts
Labels: Review effort [1-5]: 2

#261 feat: rework hand! enable by default, fix bow anim
  package.json
  pnpm-lock.yaml
  renderer/buildMesherWorker.mjs
  renderer/rsbuild.config.ts
  renderer/viewer/lib/DebugGui.ts
  renderer/viewer/lib/animationController.ts
  renderer/viewer/lib/basePlayerState.ts
  renderer/viewer/lib/cameraBobbing.ts
  renderer/viewer/lib/entities.ts
  renderer/viewer/lib/entity/EntityMesh.ts
  renderer/viewer/lib/hand.ts
  renderer/viewer/lib/holdingBlock.ts
  renderer/viewer/lib/mesher/mesher.ts
  renderer/viewer/lib/smoothSwitcher.ts
  renderer/viewer/lib/threeJsUtils.ts
  renderer/viewer/lib/utils/proxy.ts
  renderer/viewer/lib/utils/skins.ts
  renderer/viewer/lib/viewer.ts
  renderer/viewer/lib/viewerWrapper.ts
  renderer/viewer/lib/worldDataEmitter.ts
  renderer/viewer/lib/worldrendererCommon.ts
  renderer/viewer/lib/worldrendererThree.ts
  src/api/mcStatusApi.ts
  src/builtinCommands.ts
  src/devtools.ts
  src/globalState.ts
  src/index.ts
  src/inventoryWindows.ts
  src/mineflayer/playerState.ts
  src/optionsGuiScheme.tsx
  src/optionsStorage.ts
  src/parseServerAddress.ts
  src/react/AddServerOrConnect.tsx
  src/react/DebugOverlay.tsx
  src/react/GlobalSearchInput.tsx
  src/react/NoModalFoundProvider.tsx
  src/react/SignEditorProvider.tsx
  src/react/UIProvider.tsx
  src/react/utilsApp.ts
  src/reactUi.tsx
  src/rendererUtils.ts
  src/scaleInterface.ts
  src/shims/dns.js
  src/watchOptions.ts
  src/worldInteractions.ts
Labels: Review effort [1-5]: 4

#275 feat: option to disable ears on all skins
  renderer/viewer/lib/entities.ts
  renderer/viewer/lib/worldrendererCommon.ts
  src/optionsGuiScheme.tsx
  src/optionsStorage.ts
  src/watchOptions.ts
Labels: Review effort 2/5

#276 fix: autoConnect parameter wouldn't do anything
  README.MD
  src/react/AddServerOrConnect.tsx
Labels: Review effort 2/5

#277 feat: custom block models via custom channel
  renderer/viewer/lib/mesher/mesher.ts
  renderer/viewer/lib/mesher/shared.ts
  renderer/viewer/lib/mesher/world.ts
  renderer/viewer/lib/viewer.ts
  renderer/viewer/lib/worldrendererCommon.ts
  src/customChannels.ts
  src/index.ts
  src/optionsStorage.ts
  src/resourcePack.ts
Labels: Review effort 4/5

#281 fix: maps on invisible Item Frames would have gap
  renderer/viewer/lib/entities.ts
Labels: Review effort 1/5

#282 fix: floor and ceiling button hitboxes
  src/interactionShapesGenerated.json
Labels: Review effort 2/5

#283 fix: baby mobs are not rendered smaller
  renderer/viewer/lib/entities.ts
Labels: Review effort 1/5

#285 fix: improve rendering of armor to closer match game and prevent z-fighting
  renderer/viewer/lib/entity/armorModels.json
Labels: Review effort 2/5

#287 feat: Replay packets server functionality!
  README.MD
  package.json
  pnpm-lock.yaml
  src/appParams.ts
  src/browserfs.ts
  src/connect.ts
  src/controls.ts
  src/downloadAndOpenFile.ts
  src/dragndrop.ts
  src/index.ts
  src/mineflayer/plugins/localRelay.ts
  src/optionsGuiScheme.tsx
  src/packetsReplay/packetsReplayLegacy.ts
  src/packetsReplay/replayPackets.ts
  src/packetsReplayBase.ts
  src/react/AppStatusProvider.tsx
  src/react/Book.stories.tsx
  src/react/GameInteractionOverlay.tsx
  src/react/HotbarRenderApp.tsx
  src/react/NotificationProvider.tsx
  src/react/PacketsReplayProvider.tsx
  src/react/ReplayPanel.stories.tsx
  src/react/ReplayPanel.tsx
  src/react/components/replay/FilterInput.tsx
  src/react/components/replay/PacketList.tsx
  src/react/components/replay/ProgressBar.tsx
  src/react/components/replay/constants.ts
  src/react/packetsFilter.ts
  src/react/state/packetsReplayState.ts
  src/reactUi.tsx
  src/utils.ts
Labels: Review effort 4/5

#288 feat: add config option for pause screen links
  config.json
  src/globalState.ts
  src/react/DiscordButton.tsx
  src/react/PauseScreen.tsx
Labels: Review effort 2/5

#290 Add better chat link prompt screen
  src/react/MessageFormatted.tsx
Labels: Review effort 2/5

#286 feat: Refactor mouse controls, fixing all false entity/item interaction issues
  package.json
  pnpm-lock.yaml
  src/cameraRotationControls.ts
  src/devtools.ts
  src/globals.d.ts
  src/index.ts
  src/mineflayer/plugins/mouse.ts
  src/optionsStorage.ts
  src/react/GameInteractionOverlay.tsx
  src/react/TouchAreasControls.tsx
  src/worldInteractions.ts
Labels: Review effort 3/5
