Repository zardoy/minecraft-web-client, pull requests merged in 2025-05, with the labels that each got.

#341 fix: corrected scroll of main component at client mods; feat: improoved ux
  src/react/Screen.tsx
  src/react/mods.module.css
  src/screens.css
Labels: Review effort 2/5

#342 feat: Debug Response Time Indicator
  src/optionsGuiScheme.tsx
  src/optionsStorage.ts
  src/react/debugs/DebugResponseTimeIndicator.module.css
  src/react/debugs/DebugResponseTimeIndicator.module.css.d.ts
  src/react/debugs/DebugResponseTimeIndicator.tsx
  src/reactUi.tsx
Labels: Review effort 2/5

#346 feat: Entity interaction button for mobile
  src/react/TouchInteractionHint.module.css
  src/react/TouchInteractionHint.tsx
Labels: Review effort 2/5

#351 server name field "flex-start" now
  src/react/AddServerOrConnect.tsx
Labels: Review effort 1/5

#352 Entity Interaction Button works now
  src/react/TouchInteractionHint.module.css
Labels: Review effort 1/5

#348 fix: restore minimal and full map
  renderer/viewer/baseGraphicsBackend.ts
  renderer/viewer/lib/mesher/mesher.ts
  renderer/viewer/lib/mesher/models.ts
  renderer/viewer/lib/mesher/shared.ts
  renderer/viewer/lib/worldrendererCommon.ts
  src/appViewer.ts
  src/index.ts
  src/react/Minimap.tsx
  src/react/MinimapProvider.tsx
Labels: Review effort 3/5

#358 feat(config): Add support for remote dynamic splash text
  config.json
  src/appConfig.ts
  src/react/MainMenu.tsx
  src/utils/splashText.ts
Labels: Review effort 2/5

#362 fix: item textures in inventory break after loading resourcepack
  src/inventoryWindows.ts
Labels: Review effort 1/5

#363 feat: Sync armor rotation for players
  renderer/viewer/three/entities.ts
Labels: Review effort 2/5

#361 feat: configurable mobile top buttons!
  config.json
  src/appConfig.ts
  src/controls.ts
  src/globalState.ts
  src/react/DebugOverlay.tsx
  src/react/MobileTopButtons.module.css
  src/react/MobileTopButtons.module.css.d.ts
  src/react/MobileTopButtons.tsx
Labels: Review effort 3/5
