Repository zardoy/minecraft-web-client, pull requests merged in 2025-03, with the labels that each got.

#292 feat: Full support for rendering blocks in inventory GUI powered by deeplsate
  package.json
  pnpm-lock.yaml
  renderer/viewer/lib/guiRenderer.ts
  renderer/viewer/lib/worldrendererCommon.ts
  src/inventoryWindows.ts
  src/react/EnterFullscreenButton.tsx
Labels: Review effort 4/5

#293 feat: display items in hand of entities
  renderer/viewer/lib/entities.ts
  renderer/viewer/lib/entity/armorModels.json
  renderer/viewer/lib/entity/entities.json
  renderer/viewer/lib/entity/exportedModels.js
  renderer/viewer/lib/entity/models/zombie.obj
  src/index.ts
Labels: Review effort 4/5

#308 fix: respect main menu links display from config
  src/react/MainMenu.tsx
  src/react/MainMenuRenderApp.tsx
  src/react/PauseLinkButtons.tsx
  src/react/PauseScreen.tsx
Labels: Review effort 2/5

#301 feat: Add videos/images from source with protocol extension
  renderer/viewer/lib/worldrendererThree.ts
  src/customChannels.ts
  src/mineflayer/plugins/mouse.ts
  src/optionsStorage.ts
  src/react/GameInteractionOverlay.tsx
  src/react/TouchInteractionHint.tsx
Labels: Review effort 3/5

#318 feat: Item custom model data support
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  renderer/viewer/three/appShared.ts
  renderer/viewer/three/entities.ts
  src/inventoryWindows.ts
  src/mineflayer/items.ts
  src/react/HotbarRenderApp.tsx
  src/resourcePack.ts
  src/resourcesManager.ts
Labels: Review effort 2/5

#320 ci: report size change + always check single file build
  .github/workflows/bundle-stats.yml
  .github/workflows/ci.yml
  rsbuild.config.ts
Labels: Review effort 2/5
